import type { User, Internship, Application, MoU } from '@/lib/types';

export const mockUsers: User[] = [
  { id: 'student1', name: 'Aarav Sharma', email: 'student1@example.com', role: 'student', college: 'IIT Bombay', avatarUrl: 'https://picsum.photos/seed/avatar1/200/200' },
  { id: 'faculty1', name: 'Dr. Priya Singh', email: 'faculty1@example.com', role: 'faculty', college: 'IIT Bombay', avatarUrl: 'https://picsum.photos/seed/avatar2/200/200' },
  { id: 'industry1', name: 'Rohan Gupta', email: 'industry1@example.com', role: 'industry', company: 'TechNova Solutions', avatarUrl: 'https://picsum.photos/seed/avatar3/200/200' },
];

export const mockInternships: Internship[] = [
  {
    id: 'internship1',
    title: 'Frontend Developer Intern',
    companyName: 'TechNova Solutions',
    companyLogoUrl: 'https://picsum.photos/seed/logo1/200/200',
    location: 'Remote',
    duration: '3 Months',
    stipend: '₹20,000/month',
    description: 'Work on our flagship product\'s frontend using React and TypeScript. Collaborate with a dynamic team to build new features.',
    requiredSkills: ['React', 'TypeScript', 'Tailwind CSS'],
    credits: 10,
    verified: true,
    postedBy: 'industry1',
  },
  {
    id: 'internship2',
    title: 'Data Science Intern',
    companyName: 'DataWiz Inc.',
    companyLogoUrl: 'https://picsum.photos/seed/logo2/200/200',
    location: 'Bangalore',
    duration: '6 Months',
    stipend: '₹25,000/month',
    description: 'Analyze large datasets to extract meaningful insights. Build predictive models using Python and popular ML libraries.',
    requiredSkills: ['Python', 'Pandas', 'Scikit-learn', 'SQL'],
    credits: 20,
    verified: true,
    postedBy: 'industry2',
  },
  {
    id: 'internship3',
    title: 'Backend Engineer Intern',
    companyName: 'CodeCrafters',
    companyLogoUrl: 'https://picsum.photos/seed/logo3/200/200',
    location: 'Pune',
    duration: '4 Months',
    stipend: '₹22,000/month',
    description: 'Develop and maintain server-side logic, define and maintain the central database, and ensure high performance using Node.js.',
    requiredSkills: ['Node.js', 'Express', 'MongoDB', 'API Development'],
    credits: 15,
    verified: false,
    postedBy: 'industry3',
  },
  {
    id: 'internship4',
    title: 'Cloud Engineering Intern',
    companyName: 'InfraCloud',
    companyLogoUrl: 'https://picsum.photos/seed/logo4/200/200',
    location: 'Remote',
    duration: '3 Months',
    stipend: '₹28,000/month',
    description: 'Help manage and scale our cloud infrastructure on AWS. Work with technologies like Docker, Kubernetes, and Terraform.',
    requiredSkills: ['AWS', 'Docker', 'Kubernetes', 'Terraform'],
    credits: 12,
    verified: true,
    postedBy: 'industry4',
  },
  {
    id: 'internship5',
    title: 'UI/UX Design Intern',
    companyName: 'PixelPerfect',
    companyLogoUrl: 'https://picsum.photos/seed/logo5/200/200',
    location: 'Mumbai',
    duration: '2 Months',
    stipend: '₹18,000/month',
    description: 'Create intuitive and visually appealing user interfaces for web and mobile applications. Work closely with product managers and developers.',
    requiredSkills: ['Figma', 'UI/UX Design', 'Prototyping', 'Adobe XD'],
    credits: 8,
    verified: true,
    postedBy: 'industry5',
  },
  {
    id: 'internship6',
    title: 'Mobile App Developer (Android)',
    companyName: 'Appify',
    companyLogoUrl: 'https://picsum.photos/seed/logo6/200/200',
    location: 'Hyderabad',
    duration: '6 Months',
    stipend: '₹24,000/month',
    description: 'Develop native Android applications using Kotlin and Jetpack Compose. Focus on performance, UI, and user experience.',
    requiredSkills: ['Kotlin', 'Android Studio', 'Jetpack Compose', 'REST APIs'],
    credits: 20,
    verified: true,
    postedBy: 'industry6',
  },
  {
    id: 'internship7',
    title: 'Machine Learning Engineer Intern',
    companyName: 'AI Gen',
    companyLogoUrl: 'https://picsum.photos/seed/logo7/200/200',
    location: 'Bangalore',
    duration: '6 Months',
    stipend: '₹30,000/month',
    description: 'Work on developing and deploying machine learning models for natural language processing and computer vision tasks.',
    requiredSkills: ['Python', 'TensorFlow', 'PyTorch', 'Machine Learning'],
    credits: 20,
    verified: true,
    postedBy: 'industry7',
  },
  {
    id: 'internship8',
    title: 'Full-Stack Developer Intern',
    companyName: 'WebWeavers',
    companyLogoUrl: 'https://picsum.photos/seed/logo8/200/200',
    location: 'Remote',
    duration: '4 Months',
    stipend: '₹25,000/month',
    description: 'Contribute to both frontend and backend development of our web platform. A great opportunity to learn the entire stack.',
    requiredSkills: ['JavaScript', 'React', 'Node.js', 'SQL'],
    credits: 15,
    verified: false,
    postedBy: 'industry1',
  },
  {
    id: 'internship9',
    title: 'Cybersecurity Analyst Intern',
    companyName: 'SecureNet',
    companyLogoUrl: 'https://picsum.photos/seed/logo9/200/200',
    location: 'Delhi',
    duration: '3 Months',
    stipend: '₹19,000/month',
    description: 'Monitor security alerts, conduct vulnerability assessments, and assist in incident response. Learn about the latest security threats.',
    requiredSkills: ['Cybersecurity', 'Networking', 'Linux', 'Vulnerability Assessment'],
    credits: 10,
    verified: true,
    postedBy: 'industry9',
  },
  {
    id: 'internship10',
    title: 'Product Management Intern',
    companyName: 'Innovate Co.',
    companyLogoUrl: 'https://picsum.photos/seed/logo10/200/200',
    location: 'Pune',
    duration: '3 Months',
    stipend: '₹20,000/month',
    description: 'Work with our product team to define product roadmaps, write user stories, and conduct market research.',
    requiredSkills: ['Product Management', 'Market Research', 'Agile', 'Communication'],
    credits: 10,
    verified: true,
    postedBy: 'industry2',
  },
  {
    id: 'internship11',
    title: 'Digital Marketing Intern',
    companyName: 'GrowthHackers',
    companyLogoUrl: 'https://picsum.photos/seed/logo11/200/200',
    location: 'Remote',
    duration: '2 Months',
    stipend: '₹15,000/month',
    description: 'Assist in creating and managing digital marketing campaigns across various channels like social media, email, and SEO.',
    requiredSkills: ['SEO', 'Social Media Marketing', 'Content Creation', 'Google Analytics'],
    credits: 5,
    verified: true,
    postedBy: 'industry11',
  },
  {
    id: 'internship12',
    title: 'Java Developer Intern',
    companyName: 'Enterprise Solutions Ltd.',
    companyLogoUrl: 'https://picsum.photos/seed/logo12/200/200',
    location: 'Chennai',
    duration: '6 Months',
    stipend: '₹26,000/month',
    description: 'Develop robust backend services for enterprise-level applications using Java and the Spring framework.',
    requiredSkills: ['Java', 'Spring Boot', 'Microservices', 'SQL'],
    credits: 20,
    verified: true,
    postedBy: 'industry12',
  },
  {
    id: 'internship13',
    title: 'DevOps Intern',
    companyName: 'DeployFast',
    companyLogoUrl: 'https://picsum.photos/seed/logo13/200/200',
    location: 'Remote',
    duration: '4 Months',
    stipend: '₹23,000/month',
    description: 'Automate our CI/CD pipelines, manage infrastructure as code, and improve system reliability and performance.',
    requiredSkills: ['CI/CD', 'Jenkins', 'Ansible', 'Cloud Computing'],
    credits: 15,
    verified: true,
    postedBy: 'industry4',
  },
  {
    id: 'internship14',
    title: 'Graphic Design Intern',
    companyName: 'Creative Minds',
    companyLogoUrl: 'https://picsum.photos/seed/logo14/200/200',
    location: 'Mumbai',
    duration: '3 Months',
    stipend: '₹17,000/month',
    description: 'Create compelling visual assets for marketing materials, social media, and our website. A portfolio is required.',
    requiredSkills: ['Adobe Photoshop', 'Adobe Illustrator', 'Graphic Design', 'Branding'],
    credits: 10,
    verified: true,
    postedBy: 'industry5',
  },
  {
    id: 'internship15',
    title: 'Mobile App Developer (iOS)',
    companyName: 'Appify',
    companyLogoUrl: 'https://picsum.photos/seed/logo6/200/200',
    location: 'Hyderabad',
    duration: '6 Months',
    stipend: '₹24,000/month',
    description: 'Develop native iOS applications using Swift and SwiftUI. You will work on new features for our popular apps.',
    requiredSkills: ['Swift', 'SwiftUI', 'Xcode', 'REST APIs'],
    credits: 20,
    verified: true,
    postedBy: 'industry6',
  },
  {
    id: 'internship16',
    title: 'Business Analyst Intern',
    companyName: 'TechNova Solutions',
    companyLogoUrl: 'https://picsum.photos/seed/logo1/200/200',
    location: 'Pune',
    duration: '3 Months',
    stipend: '₹21,000/month',
    description: 'Gather and analyze business requirements, create process flow diagrams, and act as a bridge between business and technical teams.',
    requiredSkills: ['Business Analysis', 'SQL', 'Requirement Gathering', 'Communication'],
    credits: 10,
    verified: true,
    postedBy: 'industry1',
  },
  {
    id: 'internship17',
    title: 'Game Developer Intern (Unity)',
    companyName: 'GameOn Studios',
    companyLogoUrl: 'https://picsum.photos/seed/logo17/200/200',
    location: 'Bangalore',
    duration: '4 Months',
    stipend: '₹20,000/month',
    description: 'Work on developing new game mechanics and features for our upcoming mobile game using Unity and C#.',
    requiredSkills: ['Unity', 'C#', 'Game Development', '3D Modeling'],
    credits: 15,
    verified: false,
    postedBy: 'industry17',
  },
  {
    id: 'internship18',
    title: 'Content Writer Intern',
    companyName: 'WordSmiths',
    companyLogoUrl: 'https://picsum.photos/seed/logo18/200/200',
    location: 'Remote',
    duration: '3 Months',
    stipend: '₹16,000/month',
    description: 'Write engaging and SEO-friendly blog posts, articles, and website copy on various topics in the tech industry.',
    requiredSkills: ['Content Writing', 'SEO', 'Blogging', 'English Proficiency'],
    credits: 8,
    verified: true,
    postedBy: 'industry11',
  },
  {
    id: 'internship19',
    title: 'QA Testing Intern',
    companyName: 'BugSlayers',
    companyLogoUrl: 'https://picsum.photos/seed/logo19/200/200',
    location: 'Chennai',
    duration: '3 Months',
    stipend: '₹18,000/month',
    description: 'Perform manual and automated testing of our software to ensure quality. Write test cases and report bugs.',
    requiredSkills: ['Manual Testing', 'Automation Testing', 'JIRA', 'Selenium'],
    credits: 10,
    verified: true,
    postedBy: 'industry19',
  },
  {
    id: 'internship20',
    title: 'React Native Developer Intern',
    companyName: 'CrossPlatform',
    companyLogoUrl: 'https://picsum.photos/seed/logo20/200/200',
    location: 'Remote',
    duration: '5 Months',
    stipend: '₹27,000/month',
    description: 'Build cross-platform mobile apps for both iOS and Android using React Native. You will be part of a fast-paced agile team.',
    requiredSkills: ['React Native', 'JavaScript', 'Redux', 'API Development'],
    credits: 18,
    verified: true,
    postedBy: 'industry6',
  },
  {
    id: 'internship21',
    title: 'AI Research Intern',
    companyName: 'FutureAI Labs',
    companyLogoUrl: 'https://picsum.photos/seed/logo21/200/200',
    location: 'Bangalore',
    duration: '6 Months',
    stipend: '₹35,000/month',
    description: 'Conduct cutting-edge research in the field of deep learning and reinforcement learning. A strong mathematical background is required.',
    requiredSkills: ['Machine Learning', 'Deep Learning', 'Python', 'Research'],
    credits: 25,
    verified: true,
    postedBy: 'industry7',
  },
  {
    id: 'internship22',
    title: 'Social Media Manager Intern',
    companyName: 'Buzzworthy',
    companyLogoUrl: 'https://picsum.photos/seed/logo22/200/200',
    location: 'Mumbai',
    duration: '2 Months',
    stipend: '₹15,000/month',
    description: 'Manage and grow our social media presence on platforms like Instagram, Twitter, and LinkedIn. Create and schedule content.',
    requiredSkills: ['Social Media Marketing', 'Content Creation', 'Canva', 'Hootsuite'],
    credits: 5,
    verified: true,
    postedBy: 'industry11',
  },
  {
    id: 'internship23',
    title: 'Python/Django Developer Intern',
    companyName: 'WebCrafters',
    companyLogoUrl: 'https://picsum.photos/seed/logo23/200/200',
    location: 'Pune',
    duration: '4 Months',
    stipend: '₹24,000/month',
    description: 'Develop web applications using Python and the Django framework. Build RESTful APIs and work with databases.',
    requiredSkills: ['Python', 'Django', 'REST APIs', 'PostgreSQL'],
    credits: 15,
    verified: true,
    postedBy: 'industry3',
  },
  {
    id: 'internship24',
    title: 'Hardware Engineering Intern',
    companyName: 'ChipDesign',
    companyLogoUrl: 'https://picsum.photos/seed/logo24/200/200',
    location: 'Hyderabad',
    duration: '6 Months',
    stipend: '₹28,000/month',
    description: 'Assist in the design and testing of electronic circuits and embedded systems. Knowledge of VHDL/Verilog is a plus.',
    requiredSkills: ['Electronics', 'Circuit Design', 'VHDL', 'Embedded Systems'],
    credits: 20,
    verified: true,
    postedBy: 'industry24',
  },
  {
    id: 'internship25',
    title: 'Sales & Business Development Intern',
    companyName: 'Innovate Co.',
    companyLogoUrl: 'https://picsum.photos/seed/logo10/200/200',
    location: 'Delhi',
    duration: '3 Months',
    stipend: '₹18,000/month + Incentives',
    description: 'Identify new sales leads, pitch products to clients, and maintain good working relationships with new and existing contacts.',
    requiredSkills: ['Sales Strategy', 'Communication', 'Negotiation', 'CRM'],
    credits: 10,
    verified: true,
    postedBy: 'industry2',
  }
];

export const mockApplications: Application[] = [
  {
    id: 'app1',
    internshipId: 'internship1',
    studentId: 'student1',
    status: 'accepted',
    appliedDate: '2024-05-15',
    internshipDetails: mockInternships[0],
    studentDetails: { id: 'student1', name: 'Aarav Sharma', email: 'student1@example.com', college: 'IIT Bombay', avatarUrl: 'https://picsum.photos/seed/avatar1/200/200' },
  },
  {
    id: 'app2',
    internshipId: 'internship2',
    studentId: 'student1',
    status: 'pending',
    appliedDate: '2024-05-20',
    internshipDetails: mockInternships[1],
     studentDetails: { id: 'student1', name: 'Aarav Sharma', email: 'student1@example.com', college: 'IIT Bombay', avatarUrl: 'https://picsum.photos/seed/avatar1/200/200' },
  },
  {
    id: 'app3',
    internshipId: 'internship1',
    studentId: 'student2',
    status: 'shortlisted',
    appliedDate: '2024-05-18',
    internshipDetails: mockInternships[0],
    studentDetails: { id: 'student2', name: 'Isha Verma', email: 'student2@example.com', college: 'NIT Warangal', avatarUrl: 'https://picsum.photos/seed/avatar4/200/200' },
  },
];

export const mockMoUs: MoU[] = [
  { id: 'mou1', college: 'IIT Bombay', company: 'TechNova Solutions', validFrom: '2023-01-01', validTill: '2025-12-31', documentUrl: '#', status: 'active' },
  { id: 'mou2', college: 'IIT Bombay', company: 'DataWiz Inc.', validFrom: '2022-06-01', validTill: '2024-05-31', documentUrl: '#', status: 'expired' },
  { id: 'mou3', college: 'NIT Warangal', company: 'CodeCrafters', validFrom: '2024-03-15', validTill: '2026-03-14', documentUrl: '#', status: 'active' },
];
